# -*- coding: utf-8 -*-
"""Generates sounds/soundevents/soundevents_addon.vsndevts — the sound events of the cs2-zombie-mode sound addon.

Two kinds of events (checked on a live server):
  * 2D "for me" — round start, ambience, stinger, heartbeat, countdown: the plugin plays them to a player from
    their own pawn, key use_world_position = false;
  * 3D from an entity — zombie growls, pain, death, leap: played from the zombie's pawn so humans hear where it
    is. Do NOT set use_world_position on these: in CS2 it means "a fixed point of the map", and the growls sound
    like they come from nowhere. Positioning and falloff copy the stock Player.Death: volume curve to 1400 units,
    occlusion by walls, source raised 60 units from the feet to the head.

Music loudness lives HERE, in the event, not in the plugin: the EmitSound volume parameter does not affect these
events. Keep the plugin volumes at 1.0 and tune the numbers below.

Run: python sounds/gen_soundevents.py, then sounds/build.ps1 compiles the addon.
"""
import io
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "soundevents", "soundevents_addon.vsndevts")
ROOT = "sounds/zombiemode"

CURVE = """\t\tdistance_volume_mapping_curve =
\t\t[
\t\t\t[ 0.0, 1.0, -0.003572, -0.003572, 2.0, 3.0, ],
\t\t\t[ 150.0, 0.6, -0.00102, -0.00102, 2.0, 3.0, ],
\t\t\t[ 1400.0, 0.0, -0.000364, -0.000364, 2.0, 3.0, ],
\t\t]
"""


def flat(name, path, mixgroup=None, volume=1.0):
    """2D event: played to a player from their own pawn."""
    mg = f'\n\t\tmixgroup = "{mixgroup}"' if mixgroup else ""
    return f'''\t"{name}" =
\t{{
\t\ttype = "csgo_mega"
\t\tpreload_vsnds = true
\t\tvolume = {volume}
\t\tpitch = 1.0
\t\tuse_world_position = false{mg}
\t\tvsnd_files_track_01 = "{ROOT}/{path}"
\t}}
'''


def spatial(name, path, volume=1.0):
    """3D event from an entity, with falloff and occlusion like Player.Death."""
    return f'''\t"{name}" =
\t{{
\t\ttype = "csgo_mega"
\t\tpreload_vsnds = true
\t\tvolume = {volume}
\t\tpitch = 1.0
\t\tmixgroup = "Foley"
\t\tblock_distance = 10.0
\t\tposition_offset = [ 0.0, 0.0, 60.0 ]
\t\tocclusion_intensity = 0.9
\t\treverb_wet = 1.0
\t\treverb_source_wet = 0.5
\t\tuse_distance_volume_mapping_curve = true
{CURVE}\t\tvsnd_files_track_01 = "{ROOT}/{path}"
\t}}
'''


events = ""
# The round start track is mastered hot (peaks at 0 dBFS), so 0.2 is roughly -14 dB.
events += flat("zombiemode.round_start", "round_start.vsnd", "Music", volume=0.2)
events += flat("zombiemode.ambience", "ambience.vsnd", "Music", volume=0.35)
events += flat("zombiemode.infect", "infect_stinger.vsnd")
events += flat("zombiemode.heartbeat_slow", "heartbeat_slow.vsnd")
events += flat("zombiemode.heartbeat_medium", "heartbeat_medium.vsnd")
events += flat("zombiemode.heartbeat_fast", "heartbeat_fast.vsnd")
for n in range(1, 11):
    events += flat(f"zombiemode.count_{n}", f"countdown/{n}.vsnd")
for n in range(1, 7):
    events += spatial(f"zombiemode.zombie_idle_{n}", f"zombie/zombie_idle{n}.vsnd")
for n in range(1, 7):
    events += spatial(f"zombiemode.zombie_pain_{n}", f"zombie/zombie_pain{n}.vsnd")
for n in range(1, 7):
    # zombie_attack1..6 sound like "zombie is hurt", not like a swing, so they extend the pain pool (7..12).
    events += spatial(f"zombiemode.zombie_pain_{6 + n}", f"zombie/zombie_attack{n}.vsnd")
for n in range(1, 7):
    events += spatial(f"zombiemode.zombie_die_{n}", f"zombie/zombie_die{n}.vsnd")
for n in range(1, 7):
    events += spatial(f"zombiemode.zombie_burn_{n}", f"zombie/zombie_burn{n}.vsnd")
for n in range(1, 4):
    events += spatial(f"zombiemode.zombie_turn_{n}", f"zombie/zombie_turn{n}.vsnd")
events += spatial("zombiemode.leap", "zombie/leap.vsnd")
events += spatial("zombiemode.berserk", "zombie/berserk.vsnd")
for n in range(1, 3):
    events += flat(f"zombiemode.first_infection_{n}", f"zombie/first_infection{n}.vsnd")
for n in range(1, 7):
    events += flat(f"zombiemode.win_human_{n}", f"zombie/win_human{n}.vsnd", "Music", volume=0.5)
for n in range(1, 5):
    events += flat(f"zombiemode.win_zombie_{n}", f"zombie/win_zombie{n}.vsnd", "Music", volume=0.5)

text = '''<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
// Generated by sounds/gen_soundevents.py — edit there. Music and ambience are in the Music mix group, so the
// music slider in CS2 settings turns them down.
{
''' + events + "}\n"
os.makedirs(os.path.dirname(OUT), exist_ok=True)
io.open(OUT, "w", encoding="utf-8", newline="\n").write(text)
print("ok:", OUT, len(events.split('" =')) - 1, "events")
